import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

import Map from "../Components/Map/Map";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Client Map</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1 className={styles.title}>Client Map by Market</h1>

            <div className={styles.mapWrapper}>
                <Map />
            </div>
        </div>
    );
}
